.PHONY: all install plugin check checker clean

all install : Makefile.coq
	$(MAKE) -f Makefile.coq $@

plugin : Makefile.coq
	$(MAKE) -f Makefile.coq src/codegen_plugin.cmxs

# Makefile.coq.conf is also generated by coq_makefile.
Makefile.coq : _CoqProject
	coq_makefile -f _CoqProject -o Makefile.coq

check checker:
	cd test; $(MAKE) $@

clean :
	rm -f \
	  Makefile.coq \
	  Makefile.coq.conf \
	  src/g_codegen.ml \
	  src/*.o \ \
	  src/*.cmi \
	  src/*.cmo \
	  src/*.cmx \
	  src/*.cma \
	  src/*.cmxa \
	  src/*.cmxs \
	  src/*.a \
	  src/*.d \
	  theories/*.glob \
	  theories/*.vo \
	  theories/*.vok \
	  theories/*.vos \
	  theories/*.d \
	  test/*.cache \
	  test/test_codegen \
	  test/*.cmi \
	  test/*.cmx \
	  test/*.o \
	  test/oUnit-* \
	  sample/pow \
	  sample/rank \
	  sample/*.vo \
	  sample/*.vok \
	  sample/*.vos \
	  sample/*.glob \
	  oUnit-*

