.PHONY: all install plugin check checker clean no-install-development revert-no-install-development

-include Makefile.coq.conf

all : Makefile.coq
	$(MAKE) -f Makefile.coq $@

install : Makefile.coq
	test ! theories -ef $(COQMF_COQLIB)/user-contrib/codegen || ( echo "$(COQMF_COQLIB)/user-contrib/codegen is linked to theories.  No need to install."; false )
	$(MAKE) -f Makefile.coq $@

no-install-development : revert-no-install-development
ifdef COQMF_COQLIB
	ln -s ../src/codegen_plugin.cmi theories
	ln -s ../src/codegen_plugin.cmxs theories
	ln -s ../src/codegen_plugin.cmxa theories
	ln -s ../src/codegen_plugin.cmx theories
	ln -s `pwd`/theories $(COQMF_COQLIB)/user-contrib/codegen
else
	-echo COQMF_COQLIB not defined.  run "make" first.
endif

revert-no-install-development :
ifdef COQMF_COQLIB
	rm -f theories/codegen_plugin.cmi
	rm -f theories/codegen_plugin.cmxs
	rm -f theories/codegen_plugin.cmxa
	rm -f theories/codegen_plugin.cmx
	rm -f $(COQMF_COQLIB)/user-contrib/codegen
else
	-echo COQMF_COQLIB not defined.  run "make" first.
endif


plugin : Makefile.coq
	$(MAKE) -f Makefile.coq src/codegen_plugin.cmxs

.merlin : Makefile.coq
	$(MAKE) -f Makefile.coq .merlin

# Makefile.coq.conf is also generated by coq_makefile.
Makefile.coq : _CoqProject
	coq_makefile -f _CoqProject -o Makefile.coq

check checker:
	cd test; $(MAKE) $@

clean :
	rm -f \
	  Makefile.coq \
	  Makefile.coq.conf \
	  .Makefile.coq.d \
	  src/g_codegen.ml \
	  src/*.o \ \
	  src/*.cmi \
	  src/*.cmo \
	  src/*.cmx \
	  src/*.cma \
	  src/*.cmt \
	  src/*.cmxa \
	  src/*.cmxs \
	  src/*.a \
	  src/*.d \
	  theories/*.glob \
	  theories/*.vo \
	  theories/*.vok \
	  theories/*.vos \
	  theories/*.d \
	  theories/.*.aux \
	  test/*.cache \
	  test/test_codegen \
	  test/*.cmi \
	  test/*.cmx \
	  test/*.o \
	  test/oUnit-* \
	  sample/pow \
	  sample/rank \
	  sample/*.vo \
	  sample/*.vok \
	  sample/*.vos \
	  sample/*.glob \
	  sample/.*.aux \
	  oUnit-*

